dev:
  Type: AWS::RDS::DBInstance
  Properties:
    DBClusterIdentifier: !Ref DBCluster
    DBSubnetGroupName: !Ref DBSubnetGroup
    Engine: aurora-mysql
    EngineVersion: "5.7"
    DBInstanceClass: db.t2.medium
    PubliclyAccessible: true
  DependsOn: DBCluster
stg:
  Type: AWS::RDS::DBInstance
  Properties:
    DBClusterIdentifier: !Ref DBCluster
    DBSubnetGroupName: !Ref DBSubnetGroup
    Engine: aurora-mysql
    EngineVersion: "5.7"
    DBInstanceClass: db.t2.medium
    PubliclyAccessible: true
  DependsOn: DBCluster
prod:
  Type: AWS::RDS::DBInstance
  Properties:
    DBClusterIdentifier: !Ref DBCluster
    DBSubnetGroupName: !Ref DBSubnetGroup
    Engine: aurora-mysql
    EngineVersion: "5.7"
    DBInstanceClass: db.t2.medium
  DependsOn: DBCluster
  